### ISSUE TITLE
Tasmota intermittend Response Delay / Lag

### ISSUE THREAD

**Issue by MaxTrautwein** [MaxTrautwein/TAR-Weiterentwicklung-IoT-Tor#14]
Der ESP32 mit Tasmota Scheit teilweise erst sehr verzögert auf anfragen zu reagrien.
Dies ist auch wärend des meetings am 07.02.2022 aufgefallen

Die verzögerungszeit ist verschiden 2-13 sekunden.

Basirend auf den derzeitigen Tests verursacht **Tasmota** Dieses Problem.
- [x] Check if MQTT Settings can make a positive impact -> No Change
- [ ] Check if there are any other settings on Tasmota that make any positive impact
---

# Observed Delay (Ping in the background)

[issue6_13s_delay_Ping.zip](https://github.com/MaxTrautwein/TAR-Weiterentwicklung-IoT-Tor/files/8081743/issue6_13s_delay_Ping.zip)

```
177 66.9s Sent command Off
178 67.1s ACK (From Tasmota)

... Tasmota Responds to Ping Requests Just fine ...

208 80.4s LED Off Response (Also Visual)
```

# Observed Delay (no Ping)

[issue5_delay_Long_noPing.zip](https://github.com/MaxTrautwein/TAR-Weiterentwicklung-IoT-Tor/files/8081756/issue5_delay_Long_noPing.zip)

```
47 20s Sent command On
50 20s ACK (From Tasmota)

Between 50 & 51 15s have passed
54 45.7s Tasmota MQTT Ping

58 54.7s LED On Response (Also Visual)
```

## Notes
the ESP32 appears to recive the Ping Requests and responds to them correctly.
but the MQTT Response & Action is extreamly delayd

It seems odd that the ESP32 is sending a `ACK` imidiatly after the Request then has its "Lag" and only afterwards acts on the command.

Tasmota is not resatrting when those errors occur and I Ccan't see anything in relation to that in the logs.

**Comment by MaxTrautwein** [comment]
It is not just MQTT it is the entire ESP32 with Tasmota that is **unresponsive** for whenever this occurs.
This means that this issue is also visible on the tasmota WebServer (in that case it won't load the next page)

Given that i can browser the settings of the Router via Wifi i have to conclude that this issue is caused by **Tasmota**

_Pings however seem unaffected by this issue_

**Comment by MaxTrautwein** [comment]
This issue is caused by Tasmota not being able to reach a (any) NTP(Network Time Protocol) Server 
```
cmnd/dev/test/LedPower 0
stat/dev/test/RESULT {"LedPower1":"OFF"}
stat/dev/test/LOGGING 00:46:37.461 CFG: Saved, Count 888, Bytes 4096
stat/dev/test/LOGGING 00:46:37.541 SRC: MQTT
stat/dev/test/LOGGING 00:46:37.545 CMD: Grp 0, Cmnd 'LEDPOWER', Idx 1, Len 1, Data '0'
stat/dev/test/LOGGING 00:46:37.556 MQT: stat/dev/test/RESULT = {"LedPower1":"OFF"}
stat/dev/test/LOGGING 00:46:37.567 WIF: Checking connection...
cmnd/dev/test/LedPower 1
stat/dev/test/RESULT {"LedPower1":"ON"}
cmnd/dev/test/LedPower 0
stat/dev/test/RESULT {"LedPower1":"OFF"}
stat/dev/test/LOGGING 00:46:38.040 SRC: MQTT
stat/dev/test/LOGGING 00:46:38.044 CMD: Grp 0, Cmnd 'LEDPOWER', Idx 1, Len 1, Data '1'
stat/dev/test/LOGGING 00:46:38.055 MQT: stat/dev/test/RESULT = {"LedPower1":"ON"}
stat/dev/test/LOGGING 00:46:38.639 SRC: MQTT
stat/dev/test/LOGGING 00:46:38.642 CMD: Grp 0, Cmnd 'LEDPOWER', Idx 1, Len 1, Data '0'
stat/dev/test/LOGGING 00:46:38.655 MQT: stat/dev/test/RESULT = {"LedPower1":"OFF"}
cmnd/dev/test/LedPower 1
stat/dev/test/LOGGING 00:46:39.936 CFG: Saved, Count 889, Bytes 4096
cmnd/dev/test/LedPower 0
cmnd/dev/test/LedPower 1
stat/dev/test/RESULT {"LedPower1":"ON"}
stat/dev/test/LOGGING 00:46:39.950 NTP: Synch time...
stat/dev/test/LOGGING 00:47:07.887 NTP: Unable to resolve IP address
stat/dev/test/LOGGING 00:47:07.940 SRC: MQTT
stat/dev/test/LOGGING 00:47:07.943 CMD: Grp 0, Cmnd 'LEDPOWER', Idx 1, Len 1, Data '1'
stat/dev/test/LOGGING 00:47:07.955 MQT: stat/dev/test/RESULT = {"LedPower1":"ON"}
stat/dev/test/RESULT {"LedPower1":"OFF"}
stat/dev/test/RESULT {"LedPower1":"ON"}
stat/dev/test/LOGGING 00:47:08.065 SRC: MQTT
stat/dev/test/LOGGING 00:47:08.069 CMD: Grp 0, Cmnd 'LEDPOWER', Idx 1, Len 1, Data '0'
stat/dev/test/LOGGING 00:47:08.081 MQT: stat/dev/test/RESULT = {"LedPower1":"OFF"}
stat/dev/test/LOGGING 00:47:08.099 SRC: MQTT
stat/dev/test/LOGGING 00:47:08.103 CMD: Grp 0, Cmnd 'LEDPOWER', Idx 1, Len 1, Data '1'
stat/dev/test/LOGGING 00:47:08.112 MQT: stat/dev/test/RESULT = {"LedPower1":"ON"}
stat/dev/test/LOGGING 00:47:08.943 CFG: Saved, Count 890, Bytes 4096
```

by manually setting the time
`time 1451603800` and therefor disabeling NTP the issue can be resolved

**Comment by MaxTrautwein** [comment]
Based on some comments in the Tasmota Discord it appears as if this "Issue" is known.
the explanation seems to be that Tasmota needs a NTP server in some capacity. 

- [x] Check if the Router can host / has an internal NTP server
The Router can't Host a NTP Server
- [x] otherwise host a NTP server as part of the PI / Docker Setup

Docker Solution:
```
docker run --name=ntp --detach --publish=123:123/udp cturra/ntp
```

**Configure Tasmota to use the new server**
```
Time 0
NtpServer1 <IP>
NtpServer2 <IP>
NtpServer3 <IP>
```

**Comment by MaxTrautwein** [comment]
Dockerfile has been Updated and everything is documented in the wiki

**Comment by joymcjoy** [comment]
There is a bug in arduino core regarding ntp. Maybe esspresif has not updated. If ntp timeout occurs, a standard time should be set once during setup after reset.

**Comment by MaxTrautwein** [comment]
NTP debug / test Commands

**Win**
```
w32tm /stripchart /computer:<IP>
```

**Linux**
```
ntpdate -q <IP>
```

**Mac**
_untested_
```
sntp -d <IP>
```
